// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkv91e6RNmjmwMDPdaue5CO10O5EsS6KI',
    appId: '1:1054781568613:web:ba979e1c03048a5072b88c',
    messagingSenderId: '1054781568613',
    projectId: 'notifi-9e49f',
    authDomain: 'notifi-9e49f.firebaseapp.com',
    storageBucket: 'notifi-9e49f.appspot.com',
    measurementId: 'G-6HXGQBMTHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWxxeQMAr7EJALrY3qRQGPfnkZRLxBAkQ',
    appId: '1:1054781568613:android:ba19e360929325a272b88c',
    messagingSenderId: '1054781568613',
    projectId: 'notifi-9e49f',
    storageBucket: 'notifi-9e49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGMpKRfeHJvfEu-j36JH0MS_WonW-2iec',
    appId: '1:1054781568613:ios:e847620556523e7972b88c',
    messagingSenderId: '1054781568613',
    projectId: 'notifi-9e49f',
    storageBucket: 'notifi-9e49f.appspot.com',
    iosBundleId: 'com.example.stockeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGMpKRfeHJvfEu-j36JH0MS_WonW-2iec',
    appId: '1:1054781568613:ios:e847620556523e7972b88c',
    messagingSenderId: '1054781568613',
    projectId: 'notifi-9e49f',
    storageBucket: 'notifi-9e49f.appspot.com',
    iosBundleId: 'com.example.stockeep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkv91e6RNmjmwMDPdaue5CO10O5EsS6KI',
    appId: '1:1054781568613:web:37397005c99ca85372b88c',
    messagingSenderId: '1054781568613',
    projectId: 'notifi-9e49f',
    authDomain: 'notifi-9e49f.firebaseapp.com',
    storageBucket: 'notifi-9e49f.appspot.com',
    measurementId: 'G-9LN83QSMMM',
  );
}
